from telethon.sync import TelegramClient
from telethon.sessions import StringSession
from os import system

system("pip3 install telethon")
print("go to my.telegram.org to get your API_ID and API_HASH")
APP_ID = int(input("enter your api id: "))
API_HASH = input("enter your api has: ")


with TelegramClient(StringSession(), APP_ID, API_HASH) as client:
    session_str = client.session.save()
    message = client.send_message("me", session_str)
    message.reply("generated by @cytolytic :P")